spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}/postgres
    username: postgres
    password: '{cipher}AQB80CozWtiw7J4LWgWlJjhK+kCAkkiIC4DSbKZA7fOROx+4ThNlSrlo97xTDOTM1Bl0kf/oePiSbPCcpN+qFOp6/yhTlNmB4eir+Mk8J8l8xiMYzhBSmStktppXkJtG8QVb+cYfdWDWwnUEV9wdFzlto8QPq3/SAmgNuUpXkzaGvZ7gKfJ+/1xlltX/AWTbo/92ZzcFI3d1Ai+8jcMbEP1d8h3NEsQ+/Ox8kV0Hco7LJrxhmEoxSJPJaw8AI4khxRxteO9MOCeU/mCDaRxnaekJ708ePprIstHFwF586nsO2Uscm8rYOTonQKPp6F+4he/E7AYLaBwwPk2QZ/epZbhOfL8oDIAN2HVD4QyGaKASP2rm5AdJVhPoALUOHzGeVpw='
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
     defaultZone: http://${DISCOVERY_SERVICE_HOST:localhost}:8761/eureka/

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: true
     
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG