version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:1.0.0
    links:
     - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test:1:1"

  discovery-service:
    image: anichakra/discovery-service
    ports:
     - "8070:8070"
  
  config-service:
    image: anichakra/config-service
    ports:
     - "8060:8060"
    links:
     - kafka
     - zookeeper
    environment:
      GIT_URI: https://github.com/jass0108/configuration
      GIT_USERNAME: anichakra
      GIT_PASSWORD: Git@1345
      
  gateway-service:
    image: anichakra/gateway-service
    depends_on:
     - discovery-service
    ports:
     - "8080:8080"

  some-app-service:
    image: anichakra/some-app-service
    depends_on:
     - discovery-service
     - config-service
    ports:
     - "8180:8180"
    environment:
      POSTGRES_URL: jdbc:postgresql://http://ec2-54-221-134-89.compute-1.amazonaws.com:5432/postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres123
      
