server:
  port: 8080

spring:
  application:
    name: gateway-service

info:
  component: Edge Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  prefix: /api
  routes:
    somefeed: 
      path: /somefeed/**
      serviceId: somefeed
    fileprocessing: 
      path: /file-processing/**
      serviceId: file-processing
    kafkaproducer: 
      path: /kafka-producer/**
      serviceId: kafka-producer
    dataprocessing:
      path: /some-app-service/**
      serviceId: some-app-service 

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka
    registerWithEureka: false


logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG