version: '3'
services:
  some-app-service:
    image: anichakra/some-app-service
    ports:
     - "8180:8180"
    links:
     - config-service
     - discovery-service
     - kafka
     - zookeeper
    environment:
      POSTGRES_URL: jdbc:postgresql://ec2-35-168-228-160.compute-1.amazonaws.com:5432/postgres
      POSTGRES_USERNAME: postgres
     # POSTGRES_PASSWORD: "{cipher}aa"
      DISCOVERY_SERVICE_URL: http://discovery-service:8761/eureka
      CONFIG_SERVICE_URL: http://config-service:8888
      
