server:
  port: 8090
  
spring:  
  application:
    name: kafka-producer
  cloud:
    config:
      uri: ${CONFIG_SERVER}

eureka:  
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER}
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
          
ribbon:
  eureka:
    enabled: true
    
management:
  security:
    enabled: false  