server:  
  port: 8180
security:
  user:
    name: root
    password: s3cr3t

eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL}
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
          
ribbon:
  eureka:
    enabled: true
    
spring:
  cloud:
    config:
      uri: ${CONFIG_SERVICE_URL}
      username: root
      password: s3cr3t
      fail-fast: true

       
