server:  
  port: 8180
security:
  user:
    name: root
    password: s3cr3t

encrypt:
  key-store:
    location: classpath:/config-server.jks
    password: my-s70r3-s3cr3t
    alias: config-server-key
    secret: my-k34-s3cr3t
    
eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL}
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
          
ribbon:
  eureka:
    enabled: true
    
spring:
  cloud:
    config:
      uri: ${CONFIG_SERVICE_URL}
      username: root
      password: s3cr3t
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME} 
    password: '{cipher}AgBq3sRt3oLN52MLgsfadP0M5KYsIJvL6vTQ0AYrMjy2nYlg6fu1rP3H3I3AIrjFTF27SxsZ+/g3BL74UyETbvpitoL+E4/yaYd5Aw7KjLbnbVs39SDNWSaXrZ6QtlUb2MBaPYYsXcUd7FNYvI+7qYP3srfhGEFcu3TDuhAX3/A2QiSLGTv56I/XDbqGLU1py5vR4AEnA6OLLaBH9tdSuhMoPCgVrm371rbqzhySoyX65Nrxz7IUsWDOHxy4SpOEvYZsOVk+Mq4Rw6f/pQE6li98Zxl4RGjn0wVipPF9Qj2rO12/I6OmUoktxtu6P8SClIWOVp9vAa6wr5kuUXnXxoO/c70L9+tffWOkmvaMKqyzgKVTFOE7OgRWwzUNEfNcfUv68hCrCHQ8WGTaqxgDRrFiuTLE/2CzR5MfERCVV8k/rDwG78aC9H6FJMyH5sDtEiuDkOm9wFa3j0BaKhrYrFIHT0TGoTF9e+IpIFf93lO/odvv9QZi3HGFTjdfJ2yUxpVdFKbtVYujX+aBTHcmcTwIh3HlFpSMkZ+e4yoVZ72imVvLSShgycFf39H1qsM3BosdcJU7SQIx/s2EQj+eZRF9NRNwnxU0fFGJwJC+m3jYtYUdLa2T/g1ZlSagQ6jWaxaevqjx62oEplvUdatKe2OZmTvOdtX1j7EqdxdUiAGai/KyRfq4XrgQv3HFZFuB6fOdt3FHlGVdSsljOB/Dw2IT'
    driver-class-name: org.postgresql.Driver
    platform: postgres
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
       
