server:  
  port: 8180
security:
  user:
    name: root
    password: s3cr3t

encrypt:
  key-store:
    location: classpath:/config-server.jks
    password: my-s70r3-s3cr3t
    alias: config-server-key
    secret: my-k34-s3cr3t
    
eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL}
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
          
ribbon:
  eureka:
    enabled: true
    
spring:
  cloud:
    config:
      uri: ${CONFIG_SERVICE_URL}
      username: root
      password: s3cr3t
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME} 
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    platform: postgres
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
       
