spring:
  application:
    name: gateway-server

info:
  component: Edge Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  prefix: /api
  routes:
    somefeed: 
      path: /somefeed/**
      serviceId: somefeed
    fileprocessing: 
      path: /file-processing/**
      serviceId: file-processing
    kafkaproducer: 
      path: /kafka-producer/**
      serviceId: kafka-producer
    dataprocessing:
      path: /dataprocessing/**
      serviceId: dataprocessing 

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER}
    registerWithEureka: false
      
server:
  port: 8080

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG