server:
  port: 8075
  
spring:  
  application:
    name: kafka-producer
  cloud:
    config:
      uri: http://localhost:8888

eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8070}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
          
ribbon:
  eureka:
    enabled: true
    
management:
  security:
    enabled: false  