server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: ${git.url}
          username: ${git.username}
          password: ${git.password}
          default-label : master
    bus:
      enabled: true
    stream:
      kafka:
        binder:
          zkNodes: localhost
          defaultZkPort: 2181
          brokers: localhost
          defaultBrokerPort: 9092
  kafka:
    bootstrap-servers:
    - localhost:9092