server:
  port: 8888

security:
  user:
    name: root
    password: s3cr3t

encrypt:
  key-store:
    location: classpath:/config-server.jks
    password: my-s70r3-s3cr3t
    alias: config-server-key
    secret: my-k34-s3cr3t

spring:
  cloud:
    config:
      allow-override: true
      fail-fast: true
      server: 
        git:
          uri: ${GIT_URI}
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          default-label: master
    bus:
      enabled: true
    stream:
      kafka:
        binder:
          brokers: kafka
          zkNodes: zookeeper
  kafka:
    bootstrap-servers: kafka:9092
