server:
  port: 8060

spring:
  cloud:
    config:
      allow-override: true
      fail-fast: true
      server: 
        git:
          uri: ${GIT_URI}
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          default-label: master
    bus:
      enabled: true
    stream:
      kafka:
        binder:
          brokers: kafka
          zkNodes: zookeeper
  kafka:
    bootstrap-servers: kafka:9092
