server:
  port: 8280


spring:
  cloud:
    bus:
      enabled: true
    stream:
      kafka:
        binder:
          brokers: kafka
          zkNodes: zookeeper
  kafka:
    bootstrap-servers: kafka:9092