server:  
  port: 8888
spring:  
  cloud:
    config:
      allow-override: true
      fail-fast: true
      server: 
        git:
          uri: ${GIT_URI:https://github.com/anichakra/springboot-poc}
          username: anichakra
          #password: '{cipher}AQAwB21afoKEPZpBNY3crJdmU3b3WQ8Xlk6cIA1JfQ0AXxpq92Pv/6N0h29FnP4VDckDJUsXoWGN//PklX6SG5xJBjrF2sXpA4vBIl8Fg7pRkLFkwCP7+HIDDRym7D+QFDxrrXtGoKG3nldfMLapE3ICn7JDlBl71W3RSPlHsXWuMGXpl9jZjgKWAzFBlYC2ttQzJwZNnCMY7NQyguZXNulTT0n64jghZU6jfxL7ZnqlaeaLFirWRnJs9vK2CbHX73uvDdcqLVTbgktiS9WM/oJYJKfKoJPUIlxRkrS3MK/RqCOo1QyDaCgIM3JiofU/9upBpv0BmXOFcJt1p8NztUSFnFmjC7pxSHuHOq/xOigvGLMFxm5+Ku+C897soTh7BFA='
          password: Git@1345
          defaultLabel: master
          cloneOnStart: false
security:
  basic:
    enabled: true
  user:
    name: root
    password: s3cr3t

 