     
server:  
  port: 8888
  ssl:
    enabled: true
    key-store: classpath:eapi-ssl.jks
    key-store-password: 3@p1-s$L
    key-password: 3@p1-s$L
    key-alias: eapi-ssl

security:
  require-ssl: true
  basic:
    enabled: false
  user:
    name: root
    password: s3cr3t
    
eureka:
  #instance:
    #metadataMap:
     # user: root
      #password: s3cr3t
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL:https://localhost:8761/eureka}
    registerWithEureka: true