server:  
  port: ${PORT:8060}

eureka:  
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER}
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
          
ribbon:
  eureka:
    enabled: true
    
management:
  security:
    enabled: false
    
spring:
  cloud:
    config:
      uri: ${CONFIG_SERVER}
    bus:
        enabled: true
    stream:
      kafka:
        binder:
          zkNodes: ${ZK_HOST}
          defaultZkPort: 2181
          brokers: ${KAFKA_HOST}
          defaultBrokerPort: 9092
  kafka:
      bootstrap-servers:
      - ${KAFKA_HOST}:9092
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false